import { describe, expect, it } from 'vitest';
import {
  GENESIS,
  buildAuditChain,
  canonical,
  renderProvenanceText,
  sha256Hex,
  verifyAuditChain,
  type AuditInput,
} from '@/lib/audit';

const input: AuditInput = {
  source: { title: 'incident.pdf', kind: 'pdf', text: '37 systems were affected.' },
  ledger: { facts: [{ claim: '37 systems affected', evidence: ['seg-1'] }] },
  artifacts: [
    { format: 'advisory', content: { headline: 'Service disruption' }, model: 'test-model' },
    { format: 'linkedin', content: { body: '37 systems were affected.' }, model: 'test-model' },
  ],
  timestamp: '2026-09-25T10:00:00.000Z',
};

describe('canonical form', () => {
  it('is independent of key order', () => {
    // Otherwise the hash would depend on property insertion order and the
    // record could not be reproduced by anyone checking it.
    expect(canonical({ b: 1, a: 2 })).toBe(canonical({ a: 2, b: 1 }));
  });

  it('is not independent of array order', () => {
    expect(canonical([1, 2])).not.toBe(canonical([2, 1]));
  });

  it('sorts keys at every depth', () => {
    expect(canonical({ x: { d: 1, c: 2 } })).toBe('{"x":{"c":2,"d":1}}');
  });

  it('drops undefined rather than emitting it', () => {
    expect(canonical({ a: 1, b: undefined })).toBe('{"a":1}');
  });
});

describe('hashing', () => {
  it('produces a 64-character hex digest', async () => {
    expect(await sha256Hex('x')).toMatch(/^[0-9a-f]{64}$/);
  });

  it('matches the known digest for the empty string', async () => {
    expect(await sha256Hex('')).toBe(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    );
  });
});

describe('chain construction', () => {
  it('records the source, the ledger and every artefact in order', async () => {
    const chain = await buildAuditChain(input);

    expect(chain.map((e) => e.kind)).toEqual(['source', 'ledger', 'artifact', 'artifact']);
    expect(chain.map((e) => e.subject)).toEqual([
      'incident.pdf',
      'fact ledger',
      'advisory',
      'linkedin',
    ]);
  });

  it('starts from genesis and links each entry to the last', async () => {
    const chain = await buildAuditChain(input);

    expect(chain[0].prevHash).toBe(GENESIS);
    for (let i = 1; i < chain.length; i++) {
      expect(chain[i].prevHash).toBe(chain[i - 1].entryHash);
    }
  });

  it('is reproducible from the same inputs', async () => {
    // A record that cannot be rebuilt cannot be checked against the originals.
    expect(await buildAuditChain(input)).toEqual(await buildAuditChain(input));
  });

  it('omits the source entry in creative draft mode', async () => {
    const chain = await buildAuditChain({ ...input, source: null, ledger: undefined });

    expect(chain.every((e) => e.kind === 'artifact')).toBe(true);
    expect(chain[0].prevHash).toBe(GENESIS);
  });
});

describe('verification', () => {
  it('accepts an untouched chain', async () => {
    expect(await verifyAuditChain(await buildAuditChain(input))).toEqual({ ok: true });
  });

  it('accepts an empty chain', async () => {
    expect(await verifyAuditChain([])).toEqual({ ok: true });
  });

  it('detects edited content', async () => {
    const chain = await buildAuditChain(input);
    // Someone swaps the recorded artefact hash to match a doctored file.
    chain[2] = { ...chain[2], contentHash: await sha256Hex('doctored') };

    expect(await verifyAuditChain(chain)).toMatchObject({ ok: false, brokenAt: 2 });
  });

  it('detects an edited detail field, not just content', async () => {
    const chain = await buildAuditChain(input);
    chain[2] = { ...chain[2], detail: 'generated by a different model' };

    expect(await verifyAuditChain(chain)).toMatchObject({ ok: false, brokenAt: 2 });
  });

  it('detects a removed entry', async () => {
    const chain = await buildAuditChain(input);
    const withoutLedger = [chain[0], chain[2], chain[3]];

    // Dropping the ledger would hide what the outputs were derived from.
    expect((await verifyAuditChain(withoutLedger)).ok).toBe(false);
  });

  it('detects reordering', async () => {
    const chain = await buildAuditChain(input);
    const swapped = [chain[0], chain[1], chain[3], chain[2]];

    expect((await verifyAuditChain(swapped)).ok).toBe(false);
  });

  it('detects a re-sealed entry whose link no longer matches', async () => {
    const chain = await buildAuditChain(input);
    // A forger who reseals one entry correctly still breaks the next link.
    const forged = await buildAuditChain({
      ...input,
      artifacts: [{ format: 'advisory', content: { headline: 'Different' }, model: 'test-model' }],
    });
    chain[2] = forged[2];

    expect((await verifyAuditChain(chain)).ok).toBe(false);
  });
});

describe('readable record', () => {
  it('states what the record does and does not prove', async () => {
    const text = renderProvenanceText(await buildAuditChain(input));

    // Overclaiming here would be the exact failure the project exists to avoid.
    expect(text).toContain('not a blockchain');
    expect(text).toContain('does not verify that any generated content is correct');
  });

  it('includes every entry and the final hash', async () => {
    const chain = await buildAuditChain(input);
    const text = renderProvenanceText(chain);

    expect(text).toContain('incident.pdf');
    expect(text).toContain(chain.at(-1)!.entryHash);
  });
});
