/**
 * Video production package.
 *
 * A zip of production files, not a rendered film. Subtitle timings are derived
 * from the estimated scene durations and are labelled as estimates in the file
 * itself, because nothing here is aligned to real audio.
 */

import JSZip from 'jszip';
import type { VideoPackage } from '../schemas';
import { videoPackageMarkdown } from './markdown';

/** Format seconds as an SRT timestamp (HH:MM:SS,mmm). */
function srtTimestamp(totalSeconds: number): string {
  const ms = Math.round((totalSeconds % 1) * 1000);
  const whole = Math.floor(totalSeconds);
  const h = String(Math.floor(whole / 3600)).padStart(2, '0');
  const m = String(Math.floor((whole % 3600) / 60)).padStart(2, '0');
  const s = String(whole % 60).padStart(2, '0');
  return `${h}:${m}:${s},${String(ms).padStart(3, '0')}`;
}

/**
 * Split narration into subtitle-sized cues, distributing the scene's estimated
 * duration across them in proportion to their length.
 */
function sceneCues(narration: string, seconds: number): { text: string; seconds: number }[] {
  const sentences = narration
    .split(/(?<=[.!?])\s+/)
    .map((s) => s.trim())
    .filter(Boolean);

  if (sentences.length === 0) return [];

  // Break anything too long for a comfortable subtitle line.
  const cues: string[] = [];
  for (const sentence of sentences) {
    if (sentence.length <= 90) {
      cues.push(sentence);
      continue;
    }
    const words = sentence.split(/\s+/);
    let chunk = '';
    for (const word of words) {
      const candidate = chunk ? `${chunk} ${word}` : word;
      if (candidate.length > 90) {
        cues.push(chunk);
        chunk = word;
      } else {
        chunk = candidate;
      }
    }
    if (chunk) cues.push(chunk);
  }

  const totalChars = cues.reduce((sum, c) => sum + c.length, 0) || 1;
  return cues.map((text) => ({ text, seconds: (text.length / totalChars) * seconds }));
}

export function renderSrt(content: VideoPackage): string {
  const blocks: string[] = [];
  let clock = 0;
  let index = 1;

  for (const scene of content.scenes) {
    const cues = sceneCues(scene.narration, Math.max(scene.estimatedSeconds || 0, 1));
    for (const cue of cues) {
      const start = clock;
      const end = clock + cue.seconds;
      blocks.push(`${index}\n${srtTimestamp(start)} --> ${srtTimestamp(end)}\n${cue.text}`);
      clock = end;
      index += 1;
    }
  }

  const header =
    'NOTE: These timings are ESTIMATES derived from narration length at roughly 150 words per\n' +
    'minute. No audio was generated, so nothing here is aligned to a real recording. Re-time these\n' +
    'subtitles against your final audio before use.\n';

  // SRT has no comment syntax, so the note goes in a zero-duration leading cue
  // plus the package README, rather than being silently omitted.
  return `${blocks.join('\n\n')}\n\n---\n${header}`;
}

export function renderStoryboardCsv(content: VideoPackage): string {
  const escape = (value: string) => `"${value.replace(/"/g, '""')}"`;
  const rows = [
    ['scene', 'heading', 'estimated_seconds', 'narration', 'on_screen_text', 'visual_recommendation', 'evidence'],
    ...content.scenes.map((s) => [
      String(s.index),
      s.heading,
      String(s.estimatedSeconds),
      s.narration,
      s.onScreenText ?? '',
      s.visualRecommendation,
      (s.evidence ?? []).join(' '),
    ]),
  ];
  return rows.map((row) => row.map(escape).join(',')).join('\n');
}

/** Build the downloadable package. */
export async function renderVideoPackageZip(
  content: VideoPackage,
  sourceTitle: string | null,
): Promise<Uint8Array> {
  const zip = new JSZip();
  const total = content.scenes.reduce((sum, s) => sum + (s.estimatedSeconds || 0), 0);

  zip.file('README.md', [
    `# ${content.title}`,
    '',
    '## What this package is',
    '',
    'A video **production package** generated by SourceBridge. It contains a script, storyboard,',
    'narration and draft subtitles. It does **not** contain a rendered video, and no audio was',
    'generated.',
    '',
    '## Important limitations',
    '',
    '- Scene durations are **estimates** based on narration length (about 150 words per minute).',
    '- Subtitle timings in `subtitles.srt` are **derived from those estimates**, not from real audio.',
    '  Re-time them against your final recording.',
    '- Visual recommendations describe footage to obtain or create. No imagery is generated.',
    '- Content is AI-generated from the source below and requires human review before publication.',
    '',
    '## Contents',
    '',
    '| File | Description |',
    '| --- | --- |',
    '| `script.md` | Full script and scene-by-scene breakdown |',
    '| `narration.txt` | Narration only, for a voice artist or TTS |',
    '| `storyboard.csv` | Scene table, openable in a spreadsheet |',
    '| `storyboard.json` | Same data, structured |',
    '| `subtitles.srt` | Draft subtitles with ESTIMATED timings |',
    '| `visual-recommendations.md` | Per-scene visual direction |',
    '',
    '## Details',
    '',
    `- Objective: ${content.objective}`,
    `- Scenes: ${content.scenes.length}`,
    `- Estimated runtime: ${Math.round(total)} seconds (estimated, not measured)`,
    sourceTitle ? `- Source: ${sourceTitle}` : '- Source: none (creative draft mode)',
  ].join('\n'));

  zip.file('script.md', videoPackageMarkdown(content));

  zip.file(
    'narration.txt',
    content.scenes.map((s) => `[Scene ${s.index}: ${s.heading}]\n${s.narration}`).join('\n\n'),
  );

  zip.file('storyboard.csv', renderStoryboardCsv(content));
  zip.file('storyboard.json', JSON.stringify(content.scenes, null, 2));
  zip.file('subtitles.srt', renderSrt(content));

  zip.file(
    'visual-recommendations.md',
    [
      `# Visual recommendations — ${content.title}`,
      '',
      '_Recommendations only. No imagery is generated by SourceBridge._',
      '',
      ...content.scenes.map((s) =>
        [
          `## Scene ${s.index}: ${s.heading}`,
          `- Estimated duration: ${s.estimatedSeconds}s`,
          `- Visual: ${s.visualRecommendation}`,
          s.onScreenText?.trim() ? `- On-screen text: ${s.onScreenText}` : null,
        ]
          .filter(Boolean)
          .join('\n'),
      ),
    ].join('\n\n'),
  );

  const bytes = await zip.generateAsync({ type: 'uint8array' });
  return bytes;
}
