/**
 * Tamper-evident provenance record.
 *
 * Every export carries a hash chain: the source document, the fact ledger
 * derived from it, and each generated artefact, in order, each entry sealed
 * over the hash of the one before it. Change any recorded content after the
 * fact and the chain no longer verifies, and the break points at the entry
 * that was altered.
 *
 * This is a hash chain, not a blockchain, and the difference is stated plainly
 * wherever the record is shown. It gives integrity and ordering, which is what
 * "was this output really produced from that source?" actually requires.
 * Anchoring the final hash to an external ledger would add third-party
 * timestamping; that is a deployment decision and changes nothing here.
 *
 * What it does not do: it cannot prove the source document was authentic, or
 * that the content is correct. It proves only that this record has not been
 * edited since it was written.
 */

/** Marks the start of a chain, so the first entry still seals a predecessor. */
export const GENESIS = '0'.repeat(64);

export type AuditKind = 'source' | 'ledger' | 'artifact';

export interface AuditEntry {
  index: number;
  kind: AuditKind;
  /** What was recorded: a filename, a format id, or the ledger. */
  subject: string;
  /** Free-text context, e.g. the model that produced an artefact. */
  detail: string;
  timestamp: string;
  /** SHA-256 over the canonical form of the recorded content. */
  contentHash: string;
  /** The previous entry's entryHash, or GENESIS for the first. */
  prevHash: string;
  /** SHA-256 sealing every field above. */
  entryHash: string;
}

/**
 * Stable JSON: object keys in sorted order at every depth.
 *
 * Two runs over equal content must produce an identical string, or the hash
 * would depend on property insertion order and the record would be worthless.
 */
export function canonical(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value) ?? 'null';
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${canonical(v)}`).join(',')}}`;
}

/** Web Crypto, so this runs unchanged on the server and in the browser. */
export async function sha256Hex(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

/** The fields an entry hash is taken over: everything except the hash itself. */
const sealed = (entry: Omit<AuditEntry, 'entryHash'>) => canonical(entry);

export interface AuditInput {
  /** Null in creative draft mode, where there is no source to record. */
  source: { title: string; kind: string; text: string } | null;
  ledger?: unknown;
  artifacts: { format: string; content: unknown; model?: string }[];
  /** One timestamp for the whole record, so a chain is reproducible. */
  timestamp: string;
}

/**
 * Build the chain for one export.
 *
 * Order is part of what is sealed: source, then ledger, then artefacts as
 * given. Reordering entries breaks verification.
 */
export async function buildAuditChain(input: AuditInput): Promise<AuditEntry[]> {
  const entries: AuditEntry[] = [];
  let prevHash = GENESIS;

  const append = async (
    kind: AuditKind,
    subject: string,
    detail: string,
    content: unknown,
  ): Promise<void> => {
    const contentHash = await sha256Hex(canonical(content));
    const partial = {
      index: entries.length,
      kind,
      subject,
      detail,
      timestamp: input.timestamp,
      contentHash,
      prevHash,
    };
    const entryHash = await sha256Hex(sealed(partial));
    entries.push({ ...partial, entryHash });
    prevHash = entryHash;
  };

  if (input.source) {
    // The text, not the file bytes: it is what everything downstream was
    // actually derived from, and it is what the record can speak to.
    await append('source', input.source.title, `${input.source.kind} source`, input.source.text);
  }
  if (input.ledger !== undefined) {
    await append('ledger', 'fact ledger', 'extracted facts, figures and caveats', input.ledger);
  }
  for (const artifact of input.artifacts) {
    await append(
      'artifact',
      artifact.format,
      artifact.model ? `generated by ${artifact.model}` : 'generated',
      artifact.content,
    );
  }

  return entries;
}

export interface VerifyResult {
  ok: boolean;
  /** Index of the first entry that failed, when one did. */
  brokenAt?: number;
  reason?: string;
}

/**
 * Re-seal every entry and re-walk the links.
 *
 * Verification is self-contained: it needs only the record, so a recipient can
 * check it without the original documents or this application.
 */
export async function verifyAuditChain(entries: AuditEntry[]): Promise<VerifyResult> {
  let prevHash = GENESIS;

  for (const [i, entry] of entries.entries()) {
    if (entry.index !== i) {
      return { ok: false, brokenAt: i, reason: 'entry is out of order' };
    }
    if (entry.prevHash !== prevHash) {
      return { ok: false, brokenAt: i, reason: 'does not follow the previous entry' };
    }
    const { entryHash, ...partial } = entry;
    if ((await sha256Hex(sealed(partial))) !== entryHash) {
      return { ok: false, brokenAt: i, reason: 'entry has been altered' };
    }
    prevHash = entryHash;
  }

  return { ok: true };
}

/** The chain as a readable file, for someone who will not parse JSON. */
export function renderProvenanceText(entries: AuditEntry[]): string {
  const lines = [
    'SourceBridge provenance record',
    '',
    'A hash chain over the source, the fact ledger and every exported artefact.',
    'Each entry is sealed over the one before it, so altering any recorded',
    'content after export breaks verification at that entry.',
    '',
    'This is a hash chain, not a blockchain. It establishes integrity and',
    'ordering. It does not prove the source document was authentic, and it',
    'does not verify that any generated content is correct.',
    '',
    `Entries: ${entries.length}`,
    `Final hash: ${entries.at(-1)?.entryHash ?? '(empty chain)'}`,
    '',
  ];

  for (const entry of entries) {
    lines.push(
      `[${entry.index}] ${entry.kind}: ${entry.subject}`,
      `    ${entry.detail}`,
      `    recorded   ${entry.timestamp}`,
      `    content    sha256:${entry.contentHash}`,
      `    previous   ${entry.prevHash}`,
      `    entry      sha256:${entry.entryHash}`,
      '',
    );
  }

  lines.push(
    'To verify: recompute each entry hash over its fields in sorted-key JSON',
    'form, and check that every prevHash matches the preceding entry hash.',
  );
  return lines.join('\n');
}
